# Generated by Django 2.2.5 on 2019-09-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booz_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='post',
            name='main_alcohol',
            field=models.CharField(default='Blank slate', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='preparation',
            field=models.TextField(default='Blank slate'),
            preserve_default=False,
        ),
    ]
