# Generated by Django 2.2.5 on 2019-09-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booz_blog', '0002_auto_20190910_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blank-drink-pic.jpg', upload_to='boozula_pix'),
        ),
    ]
